server:
  port: 8180

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supermarket?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 11111
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
